port: 1337
botInvite: bot invite
guildInvite: discord invite
database:
  host: db host
  pass: db pass
  user: db user
  name: db name
discord:
  clientId: client id
  clientSecret: client secret
  redirectUri: redirect uri
  admins:
    - admin 1
    - admin 2
    - admin 3